export const SEARCH_TRACKS_BY_TITLE_REQUEST = 'SEARCH_TRACKS_BY_TITLE_REQUEST';
export const SEARCH_TRACKS_BY_TITLE_REQUEST_SUCCESS = 'SEARCH_TRACKS_BY_TITLE_REQUEST_SUCCESS';
export const SEARCH_TRACKS_BY_TITLE_REQUEST_FAIL = 'SEARCH_TRACKS_BY_TITLE_REQUEST_FAIL';
export const SEARCH_USERS_BY_NAME_REQUEST = 'SEARCH_USERS_BY_NAME_REQUEST';
export const SEARCH_USERS_BY_NAME_REQUEST_SUCCESS = 'SEARCH_USERS_BY_NAME_REQUEST_SUCCESS';
export const SEARCH_USERS_BY_NAME_REQUEST_FAIL = 'SEARCH_USERS_BY_NAME_REQUEST_FAIL';